// Top of the page will feature the color wheel. Color Wheel component.
// Playlist container with fetch for Spotify playlist based on recommendation API endpoint, using the color as the genre (multiple).
// Save to Chromeo library (right sidebar) -> saving the playlist to the Chromeo db. Can later be saved directly to Spotify.

import ColorWheel from "../components/ColorWheel";
import Navbar from "../components/Navbar";
import PlaylistContainer from "./PlaylistContainer";

// BLUE: Soft Pop, Sad, Emotional, Chill
// RED: Angry, Rock, Punk
// PURPLE: Dark, Ethereal

//User can select from up to 12 colors.
//User selects up to five colors 
//Recommendations returns an array (tracklist) generated by selections 
//User can save to Chromeo library.

//Dash State -- array of colors, playlist object (name, spotify id, array of tracks)
const tracks = [{"track"}]
const Dash = () => {
    const playlistData = {}; //mocked state data (TODO)
    const showPlayListContainer = false // mocked boolean, real: playlistData && playlistData.tracks.length
    return (
        <>
            <Navbar />
            <ColorWheel />
            {showPlayListContainer &&  <PlaylistContainer />}
        </>
    );
}
export default Dash;